In [4]:
import numpy
import math
import numpy as np
import pandas as pd

In [1]:
from google.colab import drive
drive.mount('/content/drive/')
import os
os.chdir("/content/drive/My Drive/CA683 Assignment2")

Mounted at /content/drive/

In [2]:
dict_result = {
    ('LSTM',40):'./LSTM_CV_result40.csv',
    ('LSTM',80):'./LSTM_CV_result80.csv',
    ('GRU',40):'./GRU_CV_result40.csv',
    ('GRU',80):'./GRU_CV_result80.csv',
}

In [ ]:
df_summary = pd.DataFrame(columns = ['MODEL','TRAIN_SIZE_IN_CV','MAE','MSE','RMSLE','R2'],dtype = float)
for key in dict_result.keys():
  df = pd.read_csv(dict_result[key])
  record = pd.Series({\
    'MODEL':key[0],\
    'TRAIN_SIZE_IN_CV':key[1],\
    'MAE':np.mean(df['MAE']),\
    'MSE':np.mean(df['MSE']),\
    'RMSLE':np.mean(df['RMSLE']),\
    'R2':np.mean(df['R2']),\
    },name = str(key))
  df_summary = df_summary.append(record)
df_summary

             MODEL  TRAIN_SIZE_IN_CV       MAE       MSE     RMSLE        R2
('LSTM', 40)  LSTM              40.0  0.208430  0.070868  0.032600 -0.006672
('LSTM', 80)  LSTM              80.0  0.182048  0.054212  0.028710  0.250942
('GRU', 40)    GRU              40.0  0.198708  0.064875  0.031171  0.093974
('GRU', 80)    GRU              80.0  0.175950  0.051210  0.027922  0.301806

In [ ]:
df_40 = pd.read_csv('LSTM_CV_result40.csv')
df_40 = df_40.drop('NAME',axis=1).sort_values(by='R2',ascending = False)
df_40

         ID       MAE       MSE     RMSLE         R2                name
207   49180  0.225512  0.079946  0.033918   0.686205    Emiliano Buendía
266   56087  0.160153  0.051803  0.030295   0.667434          Yerry Mina
193   63912  0.231555  0.088767  0.036674   0.648018         Patson Daka
177     509  0.133657  0.026500  0.022526   0.639624          Shane Long
352  144747  0.172922  0.048125  0.029782   0.628845          Ozan Kabak
..      ...       ...       ...       ...        ...                 ...
55    49254  0.288894  0.105887  0.042469  -2.039835  Ruben Loftus-Cheek
111   49484  0.238917  0.089385  0.037392  -2.317201      Kieran Tierney
354    1643  0.216400  0.060173  0.033874  -2.392720          Lukas Rupp
296   11657  0.364295  0.211911  0.053265  -3.367671        Fabian Schär
282   24106  0.468885  0.280184  0.069384 -11.451768          Cenk Tosun

[359 rows x 6 columns]

In [5]:
df_801 = pd.read_csv('LSTM_CV_result80.csv')
df_801 = df_801.drop('NAME',axis=1).sort_values(by='R2',ascending = False)
df_801[df_801['ID']==117]

     ID       MAE       MSE     RMSLE        R2               name
70  117  0.245155  0.097811  0.035582  0.134672  Cristiano Ronaldo

In [6]:
df_802 = pd.read_csv('GRU_CV_result80.csv')
df_802 = df_802.sort_values(by='R2',ascending = False)
df_802[df_801['ID']==117]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until

                 NAME   ID       MAE       MSE     RMSLE        R2
70  Cristiano Ronaldo  117  0.243176  0.104458  0.034611  0.290303